[workspace]
members = ["demo", "yakui-shadcn"]

[workspace.dependencies]
yakui = { git = "https://github.com/leetvr/yakui.git", branch = "main" }
yakui-core = { git = "https://github.com/leetvr/yakui.git", branch = "main" }
yakui-widgets = { git = "https://github.com/leetvr/yakui.git", branch = "main" }
